version: '3'

services:
  saferide-training:
    build: .
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./mlruns:/app/mlruns
      - ./runs:/app/runs
    environment:
      - PYTHONUNBUFFERED=1
      - KAGGLE_USERNAME=${KAGGLE_USERNAME}
      - KAGGLE_KEY=${KAGGLE_KEY}
      - CUDA_VISIBLE_DEVICES=-1